swagger: '2.0'
info:
  title: GitHub Repo Reader
  description: Read content from GitHub repositories.
  version: 1.0.0
host: api.github.com
basePath: /
schemes:
  - https
consumes:
  - application/json
produces:
  - application/json
paths:
  /repos/{owner}/{repo}/contents/{path}:
    get:
      summary: Get Repository Content
      description: Gets the contents of a file or directory.
      operationId: GetRepoContent
      parameters:
        - name: owner
          in: path
          description: Repository Owner (e.g. microsoft)
          required: true
          type: string
        - name: repo
          in: path
          description: Repository Name (e.g. vscode)
          required: true
          type: string
        - name: path
          in: path
          description: File Path (e.g. README.md)
          required: true
          type: string
      responses:
        '200':
          description: Successful response
          schema:
            type: object
            properties:
              type:
                type: string
              encoding:
                type: string
              size:
                type: integer
              name:
                type: string
              path:
                type: string
              content:
                type: string
              sha:
                type: string
              url:
                type: string
              git_url:
                type: string
              html_url:
                type: string
              download_url:
                type: string
securityDefinitions:
  BearerAuth:
    type: apiKey
    name: Authorization
    in: header
security:
  - BearerAuth: []
